kind: StorageClass
apiVersion: storage.k8s.io/v1 #必须在api-versions中存在
metadata:
  name: standard #StorageClass的名称
provisioner: kubernetes.io/glusterfs #配置PV的卷插件
parameters: #*存储类的卷的参数，取决于供应商，可以接受不同的参数，当省略参数时，使用一些默认值。
  type: io1 #体积类型 4G-16T
  iopsPerGB: "40" #iops
  fsType: ext4
reclaimPolicy: Retain #指定回收策略
allowVolumeExpansion: true #允许用户通过编辑响应的PVC来调整大小