apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-jenkins
  namespace: jenkins
spec:
  selector: #标签选择器
    matchLabels:  #必须与pv标签信息一致才可关联 如果不指定则随机匹配pv
	    app: opspv 
  resources: #资源信息
    requests: #请求容量
      storage: 20Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: standard