apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jenkins
  namespace: jenkins
spec:
  resources:
    requests:
      storage: 20Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: standard