apiVersion: v1
kind: PersistentVolume #------------资源对象
metadata: #-------------------------元数据
  name: pv0003 #--------------------PV的名称
spec: #-----------------------------定义pv模板
  capacity: #-----------------------定义pv容量
    storage: 5Gi
  accessModes: #--------------------#访问模型；对象列表 
  											            #ReadWriteOnce一人读写
  											            #ReadOnlyMany 多人只读
  											            #ReadWriteMany多人读写
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Recycle #pvc解除绑定后，数据操作
                                         #默认是Retain保留生成的数据、
                                         #recycle回收
                                         #delete，删除Delete，删除存储资源
nfs: #------------------------------挂载类型
  path: /data/tomcat #--------------nfs服务目录
  server: 172.17.0.2 #--------------nfs服务地址
  readOnly: false #-----------------关闭只读