kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim
  namespace: testmydocker #命名空间要和deployment保持一致
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
    volume.beta.kubernetes.io/storage-provisioner: fuseim.pri/ifs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
